version: '3'

dotenv: ['.env']

includes:
  client:
    taskfile: ./apps/client/Taskfile.yml
    dir: ./apps/client
  api:
    taskfile: ./apps/api/Taskfile.yml
    dir: ./apps/api

tasks:
  init:
    desc: initialize project
    cmds:
      - task: cert
      - task: traefik:init
      - curl -fsSL https://moonrepo.dev/install/moon.sh | bash
      - curl -fsSL https://moonrepo.dev/install/proto.sh | bash

  author:
    desc: display author
    cmds:
      - echo 'Romain BELLANDE'

  cert:
    desc: install certificates
    cmds:
      - mkcert -install
      - mkcert -cert-file traefik/certs/local-cert.pem -key-file traefik/certs/local-key.pem "${PROJECT_NAME}.localhost" "*.${PROJECT_NAME}.localhost"

  traefik:init:
    desc: initialize traefik configuration
    cmds:
      - docker compose run envsubst sh -c "envsubst < /wd/traefik/config.example.yml > /wd/traefik/config.yml"

  format:
    desc: format apps and packages
    cmds:
      - pnpm exec turbo format -- --no-cache
